# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.3.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./datadir:/var/lib/mysql
      - ./conf/additional.cnf:/etc/mysql/conf.d/additional.cnf
    ports:
      - "3306:3306"
